### ISSUE TITLE
Standard value for `salesActivities` field - "Finalized Deployment Need"

### ISSUE THREAD

**Issue by shiman** [aws-samples/partner-crm-integration-samples#1]
https://github.com/aws-samples/partner-crm-integration-samples/blob/299a995eb24b1a7dfb5e198a637da19a91810640/opportunity-samples/Opportunity_-_StandardValues.csv?plain=1#L8C1-L8C27

It seems one of the standard values for `salesActivities` field doesn't match with Partner Central - "Finalized Deployment Needs".

Partner Central uses a singular form:

<img width="660" alt="image" src="https://github.com/aws-samples/partner-crm-integration-samples/assets/3139481/cc071f7a-6eaf-484b-915e-673f1b76389b">

When I attempted to upload to the S3 sandbox bucket, only the singular form got accepted. If I use "Finalized Deployment Needs", I got:

```json
      "errors": [
        "Sales Activities: bad value for restricted picklist field: Finalized Deployment Needs"
      ],
```

**Comment by axmenon** [comment]
Thank you for pointing this error. We have updated the value in the [Opportunity - Standard Values sheet](https://github.com/aws-samples/partner-crm-integration-samples/blob/main/opportunity-samples/Opportunity_-_StandardValues.csv).
